version: "3.7"

services:
  rmq_main:
    image: rmq_main
    build: 
      context: ./rmq_main/
      dockerfile: Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest